CREATE DATABASE `NiklasDAOTest` /*!40100 DEFAULT CHARACTER SET latin1 */;
CREATE TABLE `TestTable` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `column1` varchar(45) DEFAULT NULL,
  `column2` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;
